const { buildListView } = require('../present/list');
const { readEventLog } = require('../snapshotSync/eventLog');

/**
 * Lists all committed versions and builds their display view — reusable
 * by cmdList or a UI backend alike.
 * @param {{store: import('../store/store').Store, snapshotsDir: string}} params
 *   `store` is required — see core/operations/show.js for the rationale.
 *   `snapshotsDir` supplies each event's own `at` timestamp (durable,
 *   recorded once in schema-snapshots/meta.json) so it can be shown
 *   alongside the commit's own timestamp (disposable, regenerated by
 *   `sync`) — see buildListView's doc comment for why both are kept.
 * @returns {Promise<ReturnType<typeof buildListView>>}
 */
async function listVersionsView({ store, snapshotsDir }) {
  const versions = await store.list();
  const log = readEventLog(snapshotsDir);
  /** @type {Object.<string, string>} */
  const eventAtById = {};
  for (const event of log.events) eventAtById[event.id] = event.at;
  return buildListView(versions, eventAtById);
}

module.exports = { listVersionsView };
