/**
 * Prints a list view (from core/present/list.js) as CLI text.
 *
 * `cache-ref` (the GitStore commit sha) is hidden by default — it's a
 * disposable id, regenerated every `sync`, so leading with it invites
 * confusion with the durable `event`/`hash` identity from
 * schema-snapshots/meta.json. Pass `showCacheRef: true` (CLI: `--show-
 * cache-ref`) to include it, e.g. when you need a value for `show`/`get`/
 * `diff`/`remove --latest`, which all take a cache-ref (see
 * docs/cli-commands.md's "Which id goes where" table).
 * @param {ReturnType<import('../../core/present/list').buildListView>} view
 * @param {{showCacheRef?: boolean}} [opts]
 */
function printListView(view, { showCacheRef = false } = {}) {
  if (view.count === 0) {
    console.log('No versions yet. Run `add <schema.json>` to commit a snapshot.');
    return;
  }

  console.log(`${view.count} version${view.count === 1 ? '' : 's'} (newest first):\n`);
  if (showCacheRef) {
    console.log('  cache-ref  event  hash     timestamp');
    for (const v of view.versions) {
      console.log(`  ${v.shortId}    ${v.event.padEnd(5)}  ${v.hash.padEnd(7)}  ${v.timestamp}`);
    }
    console.log('\ncache-ref = GitStore commit sha (disposable, regenerated by `sync`)');
    console.log('event/hash = durable identity from schema-snapshots/meta.json ("-" if not synced)');
    console.log('Use `show <cache-ref>` to inspect a version, `diff <a> <b>` to compare two.');
  } else {
    console.log('  event  hash     timestamp');
    for (const v of view.versions) {
      console.log(`  ${v.event.padEnd(5)}  ${v.hash.padEnd(7)}  ${v.timestamp}`);
    }
    console.log('\nevent/hash = durable identity from schema-snapshots/meta.json ("-" if not synced)');
    console.log('Use `remove --hash <hash>` or `--id <event>` to remove a snapshot.');
    console.log('Pass --show-cache-ref for the GitStore commit sha (needed by `show`/`get`/`diff`/`remove --latest`).');
  }
}

module.exports = { printListView };
